// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3aotG3uQD_nCXOh4UYeDTA3OVQeLgewA',
    appId: '1:163917481454:web:4cc01a569ac708475afaff',
    messagingSenderId: '163917481454',
    projectId: 'xuan-xue',
    authDomain: 'xuan-xue.firebaseapp.com',
    databaseURL: 'https://xuan-xue-default-rtdb.firebaseio.com',
    storageBucket: 'xuan-xue.firebasestorage.app',
    measurementId: 'G-CPYQHB5NFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0DbXbUQ-TMrBCT4V58J0MExC4ck59ADI',
    appId: '1:163917481454:android:acea7881d68990425afaff',
    messagingSenderId: '163917481454',
    projectId: 'xuan-xue',
    storageBucket: 'xuan-xue.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlELgARottn7xAqLCqQgVOMIQTaoNMx_8',
    appId: '1:163917481454:ios:01524531901dd47b5afaff',
    messagingSenderId: '163917481454',
    projectId: 'xuan-xue',
    storageBucket: 'xuan-xue.firebasestorage.app',
    iosBundleId: 'com.xuan.xuan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlELgARottn7xAqLCqQgVOMIQTaoNMx_8',
    appId: '1:163917481454:ios:01524531901dd47b5afaff',
    messagingSenderId: '163917481454',
    projectId: 'xuan-xue',
    storageBucket: 'xuan-xue.firebasestorage.app',
    iosBundleId: 'com.xuan.xuan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3aotG3uQD_nCXOh4UYeDTA3OVQeLgewA',
    appId: '1:163917481454:web:703fa4208b74233d5afaff',
    messagingSenderId: '163917481454',
    projectId: 'xuan-xue',
    authDomain: 'xuan-xue.firebaseapp.com',
    databaseURL: 'https://xuan-xue-default-rtdb.firebaseio.com',
    storageBucket: 'xuan-xue.firebasestorage.app',
    measurementId: 'G-D3EE7LBFQ5',
  );
}
