import 'package:common/database/tables.dart';
import 'package:drift/drift.dart';
import 'package:drift_flutter/drift_flutter.dart';
import 'package:flutter/services.dart';
import 'package:path_provider/path_provider.dart';
import '../datamodel/basic_person_info.dart';
import '../enums/enum_jia_zi.dart';
import '../models/jie_qi_info.dart';
import '../models/query_datetime.dart';
import 'connection.dart' as impl;
import 'converters/coordinates_converter.dart';
import 'converters/jie_qi_info_converter.dart';
import 'converters/location_converter.dart';
import 'daos/combined_queries_dao.dart';
import 'daos/queries_dao.dart';
import 'daos/query_datetime_dao.dart';
import 'daos/query_sub_query_type_mapper_dao.dart';
import 'daos/query_types_dao.dart';
import 'daos/seekers_dao.dart';
import 'daos/skills_dao.dart';
import 'daos/sub_query_types_dao.dart';
// Generated by drift_dev when running `build_runner build`
part 'app_database.g.dart';

@DriftDatabase(tables: [
  Queries,
  Skills,
  SkillClass,
  CombinedQueries,
  QueryDatetime,
  Seekers,
  SubQueryTypes,
  QueryTypes,
  QuerySubQueryTypeMapper,
],
    daos:[
      QueriesDao,
      SkillsDao,
      CombinedQueriesDao,
      QueryTypesDao,
      QueryDatetimeDao,
      SeekersDao,
      SubQueryTypesDao,
      QuerySubQueryTypeMapperDao,
    ],

    // include: {'sql.drift'}
)
class AppDatabase extends _$AppDatabase {
  AppDatabase([QueryExecutor? e])
      : super(
    e ??
        driftDatabase(
          name: 'app_database',
          native: const DriftNativeOptions(
            databaseDirectory: getApplicationSupportDirectory,
          ),
          web: DriftWebOptions(
            sqlite3Wasm: Uri.parse('sqlite3.wasm'),
            driftWorker: Uri.parse('drift_worker.js'),
            onResult: (result) {
              if (result.missingFeatures.isNotEmpty) {
                print(
                  'Using ${result.chosenImplementation} due to unsupported '
                      'browser features: ${result.missingFeatures}',
                );
              }
            },
          ),
        ),
  );

  // AppDatabase.forTesting(DatabaseConnection super.connection);

  @override
  int get schemaVersion => 1;

  @override
  MigrationStrategy get migration {
    return MigrationStrategy(
      onCreate: (Migrator m) async {
        await m.createAll();
        await _executeSqlScript('assets/sql/initial_data.sql');
      },
      beforeOpen: (details) async {
        // Make sure that foreign keys are enabled
        // await customStatement('PRAGMA foreign_keys = ON');

        if (details.wasCreated) {
          // Create a bunch of default values so the app doesn't look too empty
          // on the first start.

        }

        // This follows the recommendation to validate that the database schema
        // matches what drift expects (https://drift.simonbinder.eu/docs/advanced-features/migrations/#verifying-a-database-schema-at-runtime).
        // It allows catching bugs in the migration logic early.
        await impl.validateDatabaseSchema(this);
        // await impl.validateDatabaseSchema();
      },
    );
  }
  Future<void> _executeSqlScript(String scriptPath) async {
    final sqlScript = await rootBundle.loadString(scriptPath);
    final statements = sqlScript.split(';')
        .map((s) => s.trim())
        .where((s) => s.isNotEmpty)
        .toList();

    for (final statement in statements) {
      await customStatement(statement);
    }
  }
}


